#ifndef UINTA_GL_ERROR_H
#define UINTA_GL_ERROR_H

namespace uinta {

	enum gl_error_check_type {
		GL_ACTIVATE_TEXTURE,
		GL_ATTACH_SHADER,
		GL_BIND_BUFFER,
		GL_BIND_TEXTURE,
		GL_BIND_VERTEX_ARRAY,
		GL_BUFFER_DATA,
		GL_BUFFER_SUB_DATA,
		GL_CLEAR,
		GL_COMPILE_SHADER,
		GL_CREATE_PROGRAM,
		GL_CREATE_SHADER,
		GL_DELETE_BUFFERS,
		GL_DELETE_SHADER,
		GL_DELETE_VERTEX_ARRAYS,
		GL_DISABLE_VERTEX_ATTRIB_ARRAY,
		GL_DRAW_ARRAYS,
		GL_DRAW_ELEMENTS,
		GL_ENABLE_VERTEX_ATTRIB_ARRAY,
		GL_GEN_BUFFERS,
		GL_GEN_TEXTURES,
		GL_GEN_VERTEX_ARRAYS,
		GL_LINK_PROGRAM,
		GL_SHADER_SOURCE,
		GL_TEX_IMAGE2D,
		GL_TEX_PARAMETERI,
		GL_USE_PROGRAM,
		GL_VERTEX_ATTRIB_POINTER,
	};

	extern void glCheckError(gl_error_check_type type);

}

#endif //UINTA_GL_ERROR_H
