#include <uinta/gl/utils/type_utils.hpp>
#include <unordered_map>

#define GL_ENUM_LIST                                                   \
  ENTRY(GL_DEPTH_BUFFER_BIT)                                           \
  ENTRY(GL_STENCIL_BUFFER_BIT)                                         \
  ENTRY(GL_COLOR_BUFFER_BIT)                                           \
  ENTRY(GL_LINE_LOOP)                                                  \
  ENTRY(GL_LINE_STRIP)                                                 \
  ENTRY(GL_TRIANGLES)                                                  \
  ENTRY(GL_TRIANGLE_STRIP)                                             \
  ENTRY(GL_TRIANGLE_FAN)                                               \
  ENTRY(GL_NEVER)                                                      \
  ENTRY(GL_LESS)                                                       \
  ENTRY(GL_EQUAL)                                                      \
  ENTRY(GL_LEQUAL)                                                     \
  ENTRY(GL_GREATER)                                                    \
  ENTRY(GL_NOTEQUAL)                                                   \
  ENTRY(GL_GEQUAL)                                                     \
  ENTRY(GL_ALWAYS)                                                     \
  ENTRY(GL_ZERO)                                                       \
  ENTRY(GL_ONE)                                                        \
  ENTRY(GL_SRC_COLOR)                                                  \
  ENTRY(GL_ONE_MINUS_SRC_COLOR)                                        \
  ENTRY(GL_SRC_ALPHA)                                                  \
  ENTRY(GL_ONE_MINUS_SRC_ALPHA)                                        \
  ENTRY(GL_DST_ALPHA)                                                  \
  ENTRY(GL_ONE_MINUS_DST_ALPHA)                                        \
  ENTRY(GL_DST_COLOR)                                                  \
  ENTRY(GL_ONE_MINUS_DST_COLOR)                                        \
  ENTRY(GL_SRC_ALPHA_SATURATE)                                         \
  ENTRY(GL_FRONT_RIGHT)                                                \
  ENTRY(GL_BACK_LEFT)                                                  \
  ENTRY(GL_BACK_RIGHT)                                                 \
  ENTRY(GL_FRONT)                                                      \
  ENTRY(GL_BACK)                                                       \
  ENTRY(GL_LEFT)                                                       \
  ENTRY(GL_RIGHT)                                                      \
  ENTRY(GL_FRONT_AND_BACK)                                             \
  ENTRY(GL_INVALID_ENUM)                                               \
  ENTRY(GL_INVALID_VALUE)                                              \
  ENTRY(GL_INVALID_OPERATION)                                          \
  ENTRY(GL_OUT_OF_MEMORY)                                              \
  ENTRY(GL_CW)                                                         \
  ENTRY(GL_CCW)                                                        \
  ENTRY(GL_POINT_SIZE)                                                 \
  ENTRY(GL_POINT_SIZE_RANGE)                                           \
  ENTRY(GL_POINT_SIZE_GRANULARITY)                                     \
  ENTRY(GL_LINE_SMOOTH)                                                \
  ENTRY(GL_LINE_WIDTH)                                                 \
  ENTRY(GL_LINE_WIDTH_RANGE)                                           \
  ENTRY(GL_LINE_WIDTH_GRANULARITY)                                     \
  ENTRY(GL_POLYGON_MODE)                                               \
  ENTRY(GL_POLYGON_SMOOTH)                                             \
  ENTRY(GL_CULL_FACE)                                                  \
  ENTRY(GL_CULL_FACE_MODE)                                             \
  ENTRY(GL_FRONT_FACE)                                                 \
  ENTRY(GL_DEPTH_RANGE)                                                \
  ENTRY(GL_DEPTH_TEST)                                                 \
  ENTRY(GL_DEPTH_WRITEMASK)                                            \
  ENTRY(GL_DEPTH_CLEAR_VALUE)                                          \
  ENTRY(GL_DEPTH_FUNC)                                                 \
  ENTRY(GL_STENCIL_TEST)                                               \
  ENTRY(GL_STENCIL_CLEAR_VALUE)                                        \
  ENTRY(GL_STENCIL_FUNC)                                               \
  ENTRY(GL_STENCIL_VALUE_MASK)                                         \
  ENTRY(GL_STENCIL_FAIL)                                               \
  ENTRY(GL_STENCIL_PASS_DEPTH_FAIL)                                    \
  ENTRY(GL_STENCIL_PASS_DEPTH_PASS)                                    \
  ENTRY(GL_STENCIL_REF)                                                \
  ENTRY(GL_STENCIL_WRITEMASK)                                          \
  ENTRY(GL_VIEWPORT)                                                   \
  ENTRY(GL_DITHER)                                                     \
  ENTRY(GL_BLEND_DST)                                                  \
  ENTRY(GL_BLEND_SRC)                                                  \
  ENTRY(GL_BLEND)                                                      \
  ENTRY(GL_LOGIC_OP_MODE)                                              \
  ENTRY(GL_DRAW_BUFFER)                                                \
  ENTRY(GL_READ_BUFFER)                                                \
  ENTRY(GL_SCISSOR_BOX)                                                \
  ENTRY(GL_SCISSOR_TEST)                                               \
  ENTRY(GL_COLOR_CLEAR_VALUE)                                          \
  ENTRY(GL_COLOR_WRITEMASK)                                            \
  ENTRY(GL_DOUBLEBUFFER)                                               \
  ENTRY(GL_STEREO)                                                     \
  ENTRY(GL_LINE_SMOOTH_HINT)                                           \
  ENTRY(GL_POLYGON_SMOOTH_HINT)                                        \
  ENTRY(GL_UNPACK_SWAP_BYTES)                                          \
  ENTRY(GL_UNPACK_LSB_FIRST)                                           \
  ENTRY(GL_UNPACK_ROW_LENGTH)                                          \
  ENTRY(GL_UNPACK_SKIP_ROWS)                                           \
  ENTRY(GL_UNPACK_SKIP_PIXELS)                                         \
  ENTRY(GL_UNPACK_ALIGNMENT)                                           \
  ENTRY(GL_PACK_SWAP_BYTES)                                            \
  ENTRY(GL_PACK_LSB_FIRST)                                             \
  ENTRY(GL_PACK_ROW_LENGTH)                                            \
  ENTRY(GL_PACK_SKIP_ROWS)                                             \
  ENTRY(GL_PACK_SKIP_PIXELS)                                           \
  ENTRY(GL_PACK_ALIGNMENT)                                             \
  ENTRY(GL_MAX_TEXTURE_SIZE)                                           \
  ENTRY(GL_MAX_VIEWPORT_DIMS)                                          \
  ENTRY(GL_SUBPIXEL_BITS)                                              \
  ENTRY(GL_TEXTURE_1D)                                                 \
  ENTRY(GL_TEXTURE_2D)                                                 \
  ENTRY(GL_TEXTURE_WIDTH)                                              \
  ENTRY(GL_TEXTURE_HEIGHT)                                             \
  ENTRY(GL_TEXTURE_BORDER_COLOR)                                       \
  ENTRY(GL_DONT_CARE)                                                  \
  ENTRY(GL_FASTEST)                                                    \
  ENTRY(GL_NICEST)                                                     \
  ENTRY(GL_BYTE)                                                       \
  ENTRY(GL_UNSIGNED_BYTE)                                              \
  ENTRY(GL_SHORT)                                                      \
  ENTRY(GL_UNSIGNED_SHORT)                                             \
  ENTRY(GL_INT)                                                        \
  ENTRY(GL_UNSIGNED_INT)                                               \
  ENTRY(GL_FLOAT)                                                      \
  ENTRY(GL_CLEAR)                                                      \
  ENTRY(GL_AND)                                                        \
  ENTRY(GL_AND_REVERSE)                                                \
  ENTRY(GL_COPY)                                                       \
  ENTRY(GL_AND_INVERTED)                                               \
  ENTRY(GL_NOOP)                                                       \
  ENTRY(GL_XOR)                                                        \
  ENTRY(GL_OR)                                                         \
  ENTRY(GL_NOR)                                                        \
  ENTRY(GL_EQUIV)                                                      \
  ENTRY(GL_INVERT)                                                     \
  ENTRY(GL_OR_REVERSE)                                                 \
  ENTRY(GL_COPY_INVERTED)                                              \
  ENTRY(GL_OR_INVERTED)                                                \
  ENTRY(GL_NAND)                                                       \
  ENTRY(GL_SET)                                                        \
  ENTRY(GL_TEXTURE)                                                    \
  ENTRY(GL_COLOR)                                                      \
  ENTRY(GL_DEPTH)                                                      \
  ENTRY(GL_STENCIL)                                                    \
  ENTRY(GL_STENCIL_INDEX)                                              \
  ENTRY(GL_DEPTH_COMPONENT)                                            \
  ENTRY(GL_RED)                                                        \
  ENTRY(GL_GREEN)                                                      \
  ENTRY(GL_BLUE)                                                       \
  ENTRY(GL_ALPHA)                                                      \
  ENTRY(GL_RGB)                                                        \
  ENTRY(GL_RGBA)                                                       \
  ENTRY(GL_POINT)                                                      \
  ENTRY(GL_LINE)                                                       \
  ENTRY(GL_FILL)                                                       \
  ENTRY(GL_KEEP)                                                       \
  ENTRY(GL_REPLACE)                                                    \
  ENTRY(GL_INCR)                                                       \
  ENTRY(GL_DECR)                                                       \
  ENTRY(GL_VENDOR)                                                     \
  ENTRY(GL_RENDERER)                                                   \
  ENTRY(GL_VERSION)                                                    \
  ENTRY(GL_EXTENSIONS)                                                 \
  ENTRY(GL_NEAREST)                                                    \
  ENTRY(GL_LINEAR)                                                     \
  ENTRY(GL_NEAREST_MIPMAP_NEAREST)                                     \
  ENTRY(GL_LINEAR_MIPMAP_NEAREST)                                      \
  ENTRY(GL_NEAREST_MIPMAP_LINEAR)                                      \
  ENTRY(GL_LINEAR_MIPMAP_LINEAR)                                       \
  ENTRY(GL_TEXTURE_MAG_FILTER)                                         \
  ENTRY(GL_TEXTURE_MIN_FILTER)                                         \
  ENTRY(GL_TEXTURE_WRAP_S)                                             \
  ENTRY(GL_TEXTURE_WRAP_T)                                             \
  ENTRY(GL_REPEAT)                                                     \
  ENTRY(GL_COLOR_LOGIC_OP)                                             \
  ENTRY(GL_POLYGON_OFFSET_UNITS)                                       \
  ENTRY(GL_POLYGON_OFFSET_POINT)                                       \
  ENTRY(GL_POLYGON_OFFSET_LINE)                                        \
  ENTRY(GL_POLYGON_OFFSET_FILL)                                        \
  ENTRY(GL_POLYGON_OFFSET_FACTOR)                                      \
  ENTRY(GL_TEXTURE_BINDING_1D)                                         \
  ENTRY(GL_TEXTURE_BINDING_2D)                                         \
  ENTRY(GL_TEXTURE_INTERNAL_FORMAT)                                    \
  ENTRY(GL_TEXTURE_RED_SIZE)                                           \
  ENTRY(GL_TEXTURE_GREEN_SIZE)                                         \
  ENTRY(GL_TEXTURE_BLUE_SIZE)                                          \
  ENTRY(GL_TEXTURE_ALPHA_SIZE)                                         \
  ENTRY(GL_DOUBLE)                                                     \
  ENTRY(GL_PROXY_TEXTURE_1D)                                           \
  ENTRY(GL_PROXY_TEXTURE_2D)                                           \
  ENTRY(GL_R3_G3_B2)                                                   \
  ENTRY(GL_RGB4)                                                       \
  ENTRY(GL_RGB5)                                                       \
  ENTRY(GL_RGB8)                                                       \
  ENTRY(GL_RGB10)                                                      \
  ENTRY(GL_RGB12)                                                      \
  ENTRY(GL_RGB16)                                                      \
  ENTRY(GL_RGBA2)                                                      \
  ENTRY(GL_RGBA4)                                                      \
  ENTRY(GL_RGB5_A1)                                                    \
  ENTRY(GL_RGBA8)                                                      \
  ENTRY(GL_RGB10_A2)                                                   \
  ENTRY(GL_RGBA12)                                                     \
  ENTRY(GL_RGBA16)                                                     \
  ENTRY(GL_UNSIGNED_BYTE_3_3_2)                                        \
  ENTRY(GL_UNSIGNED_SHORT_4_4_4_4)                                     \
  ENTRY(GL_UNSIGNED_SHORT_5_5_5_1)                                     \
  ENTRY(GL_UNSIGNED_INT_8_8_8_8)                                       \
  ENTRY(GL_UNSIGNED_INT_10_10_10_2)                                    \
  ENTRY(GL_TEXTURE_BINDING_3D)                                         \
  ENTRY(GL_PACK_SKIP_IMAGES)                                           \
  ENTRY(GL_PACK_IMAGE_HEIGHT)                                          \
  ENTRY(GL_UNPACK_SKIP_IMAGES)                                         \
  ENTRY(GL_UNPACK_IMAGE_HEIGHT)                                        \
  ENTRY(GL_TEXTURE_3D)                                                 \
  ENTRY(GL_PROXY_TEXTURE_3D)                                           \
  ENTRY(GL_TEXTURE_DEPTH)                                              \
  ENTRY(GL_TEXTURE_WRAP_R)                                             \
  ENTRY(GL_MAX_3D_TEXTURE_SIZE)                                        \
  ENTRY(GL_UNSIGNED_BYTE_2_3_3_REV)                                    \
  ENTRY(GL_UNSIGNED_SHORT_5_6_5)                                       \
  ENTRY(GL_UNSIGNED_SHORT_5_6_5_REV)                                   \
  ENTRY(GL_UNSIGNED_SHORT_4_4_4_4_REV)                                 \
  ENTRY(GL_UNSIGNED_SHORT_1_5_5_5_REV)                                 \
  ENTRY(GL_UNSIGNED_INT_8_8_8_8_REV)                                   \
  ENTRY(GL_UNSIGNED_INT_2_10_10_10_REV)                                \
  ENTRY(GL_BGR)                                                        \
  ENTRY(GL_BGRA)                                                       \
  ENTRY(GL_MAX_ELEMENTS_VERTICES)                                      \
  ENTRY(GL_MAX_ELEMENTS_INDICES)                                       \
  ENTRY(GL_CLAMP_TO_EDGE)                                              \
  ENTRY(GL_TEXTURE_MIN_LOD)                                            \
  ENTRY(GL_TEXTURE_MAX_LOD)                                            \
  ENTRY(GL_TEXTURE_BASE_LEVEL)                                         \
  ENTRY(GL_TEXTURE_MAX_LEVEL)                                          \
  ENTRY(GL_ALIASED_LINE_WIDTH_RANGE)                                   \
  ENTRY(GL_TEXTURE0)                                                   \
  ENTRY(GL_TEXTURE1)                                                   \
  ENTRY(GL_TEXTURE2)                                                   \
  ENTRY(GL_TEXTURE3)                                                   \
  ENTRY(GL_TEXTURE4)                                                   \
  ENTRY(GL_TEXTURE5)                                                   \
  ENTRY(GL_TEXTURE6)                                                   \
  ENTRY(GL_TEXTURE7)                                                   \
  ENTRY(GL_TEXTURE8)                                                   \
  ENTRY(GL_TEXTURE9)                                                   \
  ENTRY(GL_TEXTURE10)                                                  \
  ENTRY(GL_TEXTURE11)                                                  \
  ENTRY(GL_TEXTURE12)                                                  \
  ENTRY(GL_TEXTURE13)                                                  \
  ENTRY(GL_TEXTURE14)                                                  \
  ENTRY(GL_TEXTURE15)                                                  \
  ENTRY(GL_TEXTURE16)                                                  \
  ENTRY(GL_TEXTURE17)                                                  \
  ENTRY(GL_TEXTURE18)                                                  \
  ENTRY(GL_TEXTURE19)                                                  \
  ENTRY(GL_TEXTURE20)                                                  \
  ENTRY(GL_TEXTURE21)                                                  \
  ENTRY(GL_TEXTURE22)                                                  \
  ENTRY(GL_TEXTURE23)                                                  \
  ENTRY(GL_TEXTURE24)                                                  \
  ENTRY(GL_TEXTURE25)                                                  \
  ENTRY(GL_TEXTURE26)                                                  \
  ENTRY(GL_TEXTURE27)                                                  \
  ENTRY(GL_TEXTURE28)                                                  \
  ENTRY(GL_TEXTURE29)                                                  \
  ENTRY(GL_TEXTURE30)                                                  \
  ENTRY(GL_TEXTURE31)                                                  \
  ENTRY(GL_ACTIVE_TEXTURE)                                             \
  ENTRY(GL_MULTISAMPLE)                                                \
  ENTRY(GL_SAMPLE_ALPHA_TO_COVERAGE)                                   \
  ENTRY(GL_SAMPLE_ALPHA_TO_ONE)                                        \
  ENTRY(GL_SAMPLE_COVERAGE)                                            \
  ENTRY(GL_SAMPLE_BUFFERS)                                             \
  ENTRY(GL_SAMPLES)                                                    \
  ENTRY(GL_SAMPLE_COVERAGE_VALUE)                                      \
  ENTRY(GL_SAMPLE_COVERAGE_INVERT)                                     \
  ENTRY(GL_TEXTURE_CUBE_MAP)                                           \
  ENTRY(GL_TEXTURE_BINDING_CUBE_MAP)                                   \
  ENTRY(GL_TEXTURE_CUBE_MAP_POSITIVE_X)                                \
  ENTRY(GL_TEXTURE_CUBE_MAP_NEGATIVE_X)                                \
  ENTRY(GL_TEXTURE_CUBE_MAP_POSITIVE_Y)                                \
  ENTRY(GL_TEXTURE_CUBE_MAP_NEGATIVE_Y)                                \
  ENTRY(GL_TEXTURE_CUBE_MAP_POSITIVE_Z)                                \
  ENTRY(GL_TEXTURE_CUBE_MAP_NEGATIVE_Z)                                \
  ENTRY(GL_PROXY_TEXTURE_CUBE_MAP)                                     \
  ENTRY(GL_MAX_CUBE_MAP_TEXTURE_SIZE)                                  \
  ENTRY(GL_COMPRESSED_RGB)                                             \
  ENTRY(GL_COMPRESSED_RGBA)                                            \
  ENTRY(GL_TEXTURE_COMPRESSION_HINT)                                   \
  ENTRY(GL_TEXTURE_COMPRESSED_IMAGE_SIZE)                              \
  ENTRY(GL_TEXTURE_COMPRESSED)                                         \
  ENTRY(GL_NUM_COMPRESSED_TEXTURE_FORMATS)                             \
  ENTRY(GL_COMPRESSED_TEXTURE_FORMATS)                                 \
  ENTRY(GL_CLAMP_TO_BORDER)                                            \
  ENTRY(GL_BLEND_DST_RGB)                                              \
  ENTRY(GL_BLEND_SRC_RGB)                                              \
  ENTRY(GL_BLEND_DST_ALPHA)                                            \
  ENTRY(GL_BLEND_SRC_ALPHA)                                            \
  ENTRY(GL_POINT_FADE_THRESHOLD_SIZE)                                  \
  ENTRY(GL_DEPTH_COMPONENT16)                                          \
  ENTRY(GL_DEPTH_COMPONENT24)                                          \
  ENTRY(GL_DEPTH_COMPONENT32)                                          \
  ENTRY(GL_MIRRORED_REPEAT)                                            \
  ENTRY(GL_MAX_TEXTURE_LOD_BIAS)                                       \
  ENTRY(GL_TEXTURE_LOD_BIAS)                                           \
  ENTRY(GL_INCR_WRAP)                                                  \
  ENTRY(GL_DECR_WRAP)                                                  \
  ENTRY(GL_TEXTURE_DEPTH_SIZE)                                         \
  ENTRY(GL_TEXTURE_COMPARE_MODE)                                       \
  ENTRY(GL_TEXTURE_COMPARE_FUNC)                                       \
  ENTRY(GL_BLEND_COLOR)                                                \
  ENTRY(GL_BLEND_EQUATION)                                             \
  ENTRY(GL_CONSTANT_COLOR)                                             \
  ENTRY(GL_ONE_MINUS_CONSTANT_COLOR)                                   \
  ENTRY(GL_CONSTANT_ALPHA)                                             \
  ENTRY(GL_ONE_MINUS_CONSTANT_ALPHA)                                   \
  ENTRY(GL_FUNC_ADD)                                                   \
  ENTRY(GL_FUNC_REVERSE_SUBTRACT)                                      \
  ENTRY(GL_FUNC_SUBTRACT)                                              \
  ENTRY(GL_MIN)                                                        \
  ENTRY(GL_MAX)                                                        \
  ENTRY(GL_BUFFER_SIZE)                                                \
  ENTRY(GL_BUFFER_USAGE)                                               \
  ENTRY(GL_QUERY_COUNTER_BITS)                                         \
  ENTRY(GL_CURRENT_QUERY)                                              \
  ENTRY(GL_QUERY_RESULT)                                               \
  ENTRY(GL_QUERY_RESULT_AVAILABLE)                                     \
  ENTRY(GL_ARRAY_BUFFER)                                               \
  ENTRY(GL_ELEMENT_ARRAY_BUFFER)                                       \
  ENTRY(GL_ARRAY_BUFFER_BINDING)                                       \
  ENTRY(GL_ELEMENT_ARRAY_BUFFER_BINDING)                               \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING)                         \
  ENTRY(GL_READ_ONLY)                                                  \
  ENTRY(GL_WRITE_ONLY)                                                 \
  ENTRY(GL_READ_WRITE)                                                 \
  ENTRY(GL_BUFFER_ACCESS)                                              \
  ENTRY(GL_BUFFER_MAPPED)                                              \
  ENTRY(GL_BUFFER_MAP_POINTER)                                         \
  ENTRY(GL_STREAM_DRAW)                                                \
  ENTRY(GL_STREAM_READ)                                                \
  ENTRY(GL_STREAM_COPY)                                                \
  ENTRY(GL_STATIC_DRAW)                                                \
  ENTRY(GL_STATIC_READ)                                                \
  ENTRY(GL_STATIC_COPY)                                                \
  ENTRY(GL_DYNAMIC_DRAW)                                               \
  ENTRY(GL_DYNAMIC_READ)                                               \
  ENTRY(GL_DYNAMIC_COPY)                                               \
  ENTRY(GL_SAMPLES_PASSED)                                             \
  ENTRY(GL_SRC1_ALPHA)                                                 \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_ENABLED)                                \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_SIZE)                                   \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_STRIDE)                                 \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_TYPE)                                   \
  ENTRY(GL_CURRENT_VERTEX_ATTRIB)                                      \
  ENTRY(GL_VERTEX_PROGRAM_POINT_SIZE)                                  \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_POINTER)                                \
  ENTRY(GL_STENCIL_BACK_FUNC)                                          \
  ENTRY(GL_STENCIL_BACK_FAIL)                                          \
  ENTRY(GL_STENCIL_BACK_PASS_DEPTH_FAIL)                               \
  ENTRY(GL_STENCIL_BACK_PASS_DEPTH_PASS)                               \
  ENTRY(GL_MAX_DRAW_BUFFERS)                                           \
  ENTRY(GL_DRAW_BUFFER0)                                               \
  ENTRY(GL_DRAW_BUFFER1)                                               \
  ENTRY(GL_DRAW_BUFFER2)                                               \
  ENTRY(GL_DRAW_BUFFER3)                                               \
  ENTRY(GL_DRAW_BUFFER4)                                               \
  ENTRY(GL_DRAW_BUFFER5)                                               \
  ENTRY(GL_DRAW_BUFFER6)                                               \
  ENTRY(GL_DRAW_BUFFER7)                                               \
  ENTRY(GL_DRAW_BUFFER8)                                               \
  ENTRY(GL_DRAW_BUFFER9)                                               \
  ENTRY(GL_DRAW_BUFFER10)                                              \
  ENTRY(GL_DRAW_BUFFER11)                                              \
  ENTRY(GL_DRAW_BUFFER12)                                              \
  ENTRY(GL_DRAW_BUFFER13)                                              \
  ENTRY(GL_DRAW_BUFFER14)                                              \
  ENTRY(GL_DRAW_BUFFER15)                                              \
  ENTRY(GL_BLEND_EQUATION_ALPHA)                                       \
  ENTRY(GL_MAX_VERTEX_ATTRIBS)                                         \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_NORMALIZED)                             \
  ENTRY(GL_MAX_TEXTURE_IMAGE_UNITS)                                    \
  ENTRY(GL_FRAGMENT_SHADER)                                            \
  ENTRY(GL_VERTEX_SHADER)                                              \
  ENTRY(GL_MAX_FRAGMENT_UNIFORM_COMPONENTS)                            \
  ENTRY(GL_MAX_VERTEX_UNIFORM_COMPONENTS)                              \
  ENTRY(GL_MAX_VARYING_FLOATS)                                         \
  ENTRY(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS)                             \
  ENTRY(GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS)                           \
  ENTRY(GL_SHADER_TYPE)                                                \
  ENTRY(GL_FLOAT_VEC2)                                                 \
  ENTRY(GL_FLOAT_VEC3)                                                 \
  ENTRY(GL_FLOAT_VEC4)                                                 \
  ENTRY(GL_INT_VEC2)                                                   \
  ENTRY(GL_INT_VEC3)                                                   \
  ENTRY(GL_INT_VEC4)                                                   \
  ENTRY(GL_BOOL)                                                       \
  ENTRY(GL_BOOL_VEC2)                                                  \
  ENTRY(GL_BOOL_VEC3)                                                  \
  ENTRY(GL_BOOL_VEC4)                                                  \
  ENTRY(GL_FLOAT_MAT2)                                                 \
  ENTRY(GL_FLOAT_MAT3)                                                 \
  ENTRY(GL_FLOAT_MAT4)                                                 \
  ENTRY(GL_SAMPLER_1D)                                                 \
  ENTRY(GL_SAMPLER_2D)                                                 \
  ENTRY(GL_SAMPLER_3D)                                                 \
  ENTRY(GL_SAMPLER_CUBE)                                               \
  ENTRY(GL_SAMPLER_1D_SHADOW)                                          \
  ENTRY(GL_SAMPLER_2D_SHADOW)                                          \
  ENTRY(GL_DELETE_STATUS)                                              \
  ENTRY(GL_COMPILE_STATUS)                                             \
  ENTRY(GL_LINK_STATUS)                                                \
  ENTRY(GL_VALIDATE_STATUS)                                            \
  ENTRY(GL_INFO_LOG_LENGTH)                                            \
  ENTRY(GL_ATTACHED_SHADERS)                                           \
  ENTRY(GL_ACTIVE_UNIFORMS)                                            \
  ENTRY(GL_ACTIVE_UNIFORM_MAX_LENGTH)                                  \
  ENTRY(GL_SHADER_SOURCE_LENGTH)                                       \
  ENTRY(GL_ACTIVE_ATTRIBUTES)                                          \
  ENTRY(GL_ACTIVE_ATTRIBUTE_MAX_LENGTH)                                \
  ENTRY(GL_FRAGMENT_SHADER_DERIVATIVE_HINT)                            \
  ENTRY(GL_SHADING_LANGUAGE_VERSION)                                   \
  ENTRY(GL_CURRENT_PROGRAM)                                            \
  ENTRY(GL_POINT_SPRITE_COORD_ORIGIN)                                  \
  ENTRY(GL_LOWER_LEFT)                                                 \
  ENTRY(GL_UPPER_LEFT)                                                 \
  ENTRY(GL_STENCIL_BACK_REF)                                           \
  ENTRY(GL_STENCIL_BACK_VALUE_MASK)                                    \
  ENTRY(GL_STENCIL_BACK_WRITEMASK)                                     \
  ENTRY(GL_PIXEL_PACK_BUFFER)                                          \
  ENTRY(GL_PIXEL_UNPACK_BUFFER)                                        \
  ENTRY(GL_PIXEL_PACK_BUFFER_BINDING)                                  \
  ENTRY(GL_PIXEL_UNPACK_BUFFER_BINDING)                                \
  ENTRY(GL_FLOAT_MAT2x3)                                               \
  ENTRY(GL_FLOAT_MAT2x4)                                               \
  ENTRY(GL_FLOAT_MAT3x2)                                               \
  ENTRY(GL_FLOAT_MAT3x4)                                               \
  ENTRY(GL_FLOAT_MAT4x2)                                               \
  ENTRY(GL_FLOAT_MAT4x3)                                               \
  ENTRY(GL_SRGB)                                                       \
  ENTRY(GL_SRGB8)                                                      \
  ENTRY(GL_SRGB_ALPHA)                                                 \
  ENTRY(GL_SRGB8_ALPHA8)                                               \
  ENTRY(GL_COMPRESSED_SRGB)                                            \
  ENTRY(GL_COMPRESSED_SRGB_ALPHA)                                      \
  ENTRY(GL_COMPARE_REF_TO_TEXTURE)                                     \
  ENTRY(GL_CLIP_DISTANCE0)                                             \
  ENTRY(GL_CLIP_DISTANCE1)                                             \
  ENTRY(GL_CLIP_DISTANCE2)                                             \
  ENTRY(GL_CLIP_DISTANCE3)                                             \
  ENTRY(GL_CLIP_DISTANCE4)                                             \
  ENTRY(GL_CLIP_DISTANCE5)                                             \
  ENTRY(GL_CLIP_DISTANCE6)                                             \
  ENTRY(GL_CLIP_DISTANCE7)                                             \
  ENTRY(GL_MAX_CLIP_DISTANCES)                                         \
  ENTRY(GL_MAJOR_VERSION)                                              \
  ENTRY(GL_MINOR_VERSION)                                              \
  ENTRY(GL_NUM_EXTENSIONS)                                             \
  ENTRY(GL_CONTEXT_FLAGS)                                              \
  ENTRY(GL_COMPRESSED_RED)                                             \
  ENTRY(GL_COMPRESSED_RG)                                              \
  ENTRY(GL_RGBA32F)                                                    \
  ENTRY(GL_RGB32F)                                                     \
  ENTRY(GL_RGBA16F)                                                    \
  ENTRY(GL_RGB16F)                                                     \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_INTEGER)                                \
  ENTRY(GL_MAX_ARRAY_TEXTURE_LAYERS)                                   \
  ENTRY(GL_MIN_PROGRAM_TEXEL_OFFSET)                                   \
  ENTRY(GL_MAX_PROGRAM_TEXEL_OFFSET)                                   \
  ENTRY(GL_CLAMP_READ_COLOR)                                           \
  ENTRY(GL_FIXED_ONLY)                                                 \
  ENTRY(GL_TEXTURE_1D_ARRAY)                                           \
  ENTRY(GL_PROXY_TEXTURE_1D_ARRAY)                                     \
  ENTRY(GL_TEXTURE_2D_ARRAY)                                           \
  ENTRY(GL_PROXY_TEXTURE_2D_ARRAY)                                     \
  ENTRY(GL_TEXTURE_BINDING_1D_ARRAY)                                   \
  ENTRY(GL_TEXTURE_BINDING_2D_ARRAY)                                   \
  ENTRY(GL_R11F_G11F_B10F)                                             \
  ENTRY(GL_UNSIGNED_INT_10F_11F_11F_REV)                               \
  ENTRY(GL_RGB9_E5)                                                    \
  ENTRY(GL_UNSIGNED_INT_5_9_9_9_REV)                                   \
  ENTRY(GL_TEXTURE_SHARED_SIZE)                                        \
  ENTRY(GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH)                      \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_MODE)                             \
  ENTRY(GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS)                 \
  ENTRY(GL_TRANSFORM_FEEDBACK_VARYINGS)                                \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_START)                            \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_SIZE)                             \
  ENTRY(GL_PRIMITIVES_GENERATED)                                       \
  ENTRY(GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN)                      \
  ENTRY(GL_RASTERIZER_DISCARD)                                         \
  ENTRY(GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS)              \
  ENTRY(GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS)                    \
  ENTRY(GL_INTERLEAVED_ATTRIBS)                                        \
  ENTRY(GL_SEPARATE_ATTRIBS)                                           \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER)                                  \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_BINDING)                          \
  ENTRY(GL_RGBA32UI)                                                   \
  ENTRY(GL_RGB32UI)                                                    \
  ENTRY(GL_RGBA16UI)                                                   \
  ENTRY(GL_RGB16UI)                                                    \
  ENTRY(GL_RGBA8UI)                                                    \
  ENTRY(GL_RGB8UI)                                                     \
  ENTRY(GL_RGBA32I)                                                    \
  ENTRY(GL_RGB32I)                                                     \
  ENTRY(GL_RGBA16I)                                                    \
  ENTRY(GL_RGB16I)                                                     \
  ENTRY(GL_RGBA8I)                                                     \
  ENTRY(GL_RGB8I)                                                      \
  ENTRY(GL_RED_INTEGER)                                                \
  ENTRY(GL_GREEN_INTEGER)                                              \
  ENTRY(GL_BLUE_INTEGER)                                               \
  ENTRY(GL_RGB_INTEGER)                                                \
  ENTRY(GL_RGBA_INTEGER)                                               \
  ENTRY(GL_BGR_INTEGER)                                                \
  ENTRY(GL_BGRA_INTEGER)                                               \
  ENTRY(GL_SAMPLER_1D_ARRAY)                                           \
  ENTRY(GL_SAMPLER_2D_ARRAY)                                           \
  ENTRY(GL_SAMPLER_1D_ARRAY_SHADOW)                                    \
  ENTRY(GL_SAMPLER_2D_ARRAY_SHADOW)                                    \
  ENTRY(GL_SAMPLER_CUBE_SHADOW)                                        \
  ENTRY(GL_UNSIGNED_INT_VEC2)                                          \
  ENTRY(GL_UNSIGNED_INT_VEC3)                                          \
  ENTRY(GL_UNSIGNED_INT_VEC4)                                          \
  ENTRY(GL_INT_SAMPLER_1D)                                             \
  ENTRY(GL_INT_SAMPLER_2D)                                             \
  ENTRY(GL_INT_SAMPLER_3D)                                             \
  ENTRY(GL_INT_SAMPLER_CUBE)                                           \
  ENTRY(GL_INT_SAMPLER_1D_ARRAY)                                       \
  ENTRY(GL_INT_SAMPLER_2D_ARRAY)                                       \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_1D)                                    \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_2D)                                    \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_3D)                                    \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_CUBE)                                  \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_1D_ARRAY)                              \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_2D_ARRAY)                              \
  ENTRY(GL_QUERY_WAIT)                                                 \
  ENTRY(GL_QUERY_NO_WAIT)                                              \
  ENTRY(GL_QUERY_BY_REGION_WAIT)                                       \
  ENTRY(GL_QUERY_BY_REGION_NO_WAIT)                                    \
  ENTRY(GL_BUFFER_ACCESS_FLAGS)                                        \
  ENTRY(GL_BUFFER_MAP_LENGTH)                                          \
  ENTRY(GL_BUFFER_MAP_OFFSET)                                          \
  ENTRY(GL_DEPTH_COMPONENT32F)                                         \
  ENTRY(GL_DEPTH32F_STENCIL8)                                          \
  ENTRY(GL_FLOAT_32_UNSIGNED_INT_24_8_REV)                             \
  ENTRY(GL_INVALID_FRAMEBUFFER_OPERATION)                              \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING)                      \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE)                      \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE)                            \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE)                          \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE)                           \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE)                          \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE)                          \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE)                        \
  ENTRY(GL_FRAMEBUFFER_DEFAULT)                                        \
  ENTRY(GL_FRAMEBUFFER_UNDEFINED)                                      \
  ENTRY(GL_DEPTH_STENCIL_ATTACHMENT)                                   \
  ENTRY(GL_MAX_RENDERBUFFER_SIZE)                                      \
  ENTRY(GL_DEPTH_STENCIL)                                              \
  ENTRY(GL_UNSIGNED_INT_24_8)                                          \
  ENTRY(GL_DEPTH24_STENCIL8)                                           \
  ENTRY(GL_TEXTURE_STENCIL_SIZE)                                       \
  ENTRY(GL_TEXTURE_RED_TYPE)                                           \
  ENTRY(GL_TEXTURE_GREEN_TYPE)                                         \
  ENTRY(GL_TEXTURE_BLUE_TYPE)                                          \
  ENTRY(GL_TEXTURE_ALPHA_TYPE)                                         \
  ENTRY(GL_TEXTURE_DEPTH_TYPE)                                         \
  ENTRY(GL_UNSIGNED_NORMALIZED)                                        \
  ENTRY(GL_FRAMEBUFFER_BINDING)                                        \
  ENTRY(GL_RENDERBUFFER_BINDING)                                       \
  ENTRY(GL_READ_FRAMEBUFFER)                                           \
  ENTRY(GL_DRAW_FRAMEBUFFER)                                           \
  ENTRY(GL_READ_FRAMEBUFFER_BINDING)                                   \
  ENTRY(GL_RENDERBUFFER_SAMPLES)                                       \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE)                         \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME)                         \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL)                       \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE)               \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER)                       \
  ENTRY(GL_FRAMEBUFFER_COMPLETE)                                       \
  ENTRY(GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT)                          \
  ENTRY(GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT)                  \
  ENTRY(GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER)                         \
  ENTRY(GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER)                         \
  ENTRY(GL_FRAMEBUFFER_UNSUPPORTED)                                    \
  ENTRY(GL_MAX_COLOR_ATTACHMENTS)                                      \
  ENTRY(GL_COLOR_ATTACHMENT0)                                          \
  ENTRY(GL_COLOR_ATTACHMENT1)                                          \
  ENTRY(GL_COLOR_ATTACHMENT2)                                          \
  ENTRY(GL_COLOR_ATTACHMENT3)                                          \
  ENTRY(GL_COLOR_ATTACHMENT4)                                          \
  ENTRY(GL_COLOR_ATTACHMENT5)                                          \
  ENTRY(GL_COLOR_ATTACHMENT6)                                          \
  ENTRY(GL_COLOR_ATTACHMENT7)                                          \
  ENTRY(GL_COLOR_ATTACHMENT8)                                          \
  ENTRY(GL_COLOR_ATTACHMENT9)                                          \
  ENTRY(GL_COLOR_ATTACHMENT10)                                         \
  ENTRY(GL_COLOR_ATTACHMENT11)                                         \
  ENTRY(GL_COLOR_ATTACHMENT12)                                         \
  ENTRY(GL_COLOR_ATTACHMENT13)                                         \
  ENTRY(GL_COLOR_ATTACHMENT14)                                         \
  ENTRY(GL_COLOR_ATTACHMENT15)                                         \
  ENTRY(GL_COLOR_ATTACHMENT16)                                         \
  ENTRY(GL_COLOR_ATTACHMENT17)                                         \
  ENTRY(GL_COLOR_ATTACHMENT18)                                         \
  ENTRY(GL_COLOR_ATTACHMENT19)                                         \
  ENTRY(GL_COLOR_ATTACHMENT20)                                         \
  ENTRY(GL_COLOR_ATTACHMENT21)                                         \
  ENTRY(GL_COLOR_ATTACHMENT22)                                         \
  ENTRY(GL_COLOR_ATTACHMENT23)                                         \
  ENTRY(GL_COLOR_ATTACHMENT24)                                         \
  ENTRY(GL_COLOR_ATTACHMENT25)                                         \
  ENTRY(GL_COLOR_ATTACHMENT26)                                         \
  ENTRY(GL_COLOR_ATTACHMENT27)                                         \
  ENTRY(GL_COLOR_ATTACHMENT28)                                         \
  ENTRY(GL_COLOR_ATTACHMENT29)                                         \
  ENTRY(GL_COLOR_ATTACHMENT30)                                         \
  ENTRY(GL_COLOR_ATTACHMENT31)                                         \
  ENTRY(GL_DEPTH_ATTACHMENT)                                           \
  ENTRY(GL_STENCIL_ATTACHMENT)                                         \
  ENTRY(GL_FRAMEBUFFER)                                                \
  ENTRY(GL_RENDERBUFFER)                                               \
  ENTRY(GL_RENDERBUFFER_WIDTH)                                         \
  ENTRY(GL_RENDERBUFFER_HEIGHT)                                        \
  ENTRY(GL_RENDERBUFFER_INTERNAL_FORMAT)                               \
  ENTRY(GL_STENCIL_INDEX1)                                             \
  ENTRY(GL_STENCIL_INDEX4)                                             \
  ENTRY(GL_STENCIL_INDEX8)                                             \
  ENTRY(GL_STENCIL_INDEX16)                                            \
  ENTRY(GL_RENDERBUFFER_RED_SIZE)                                      \
  ENTRY(GL_RENDERBUFFER_GREEN_SIZE)                                    \
  ENTRY(GL_RENDERBUFFER_BLUE_SIZE)                                     \
  ENTRY(GL_RENDERBUFFER_ALPHA_SIZE)                                    \
  ENTRY(GL_RENDERBUFFER_DEPTH_SIZE)                                    \
  ENTRY(GL_RENDERBUFFER_STENCIL_SIZE)                                  \
  ENTRY(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE)                         \
  ENTRY(GL_MAX_SAMPLES)                                                \
  ENTRY(GL_FRAMEBUFFER_SRGB)                                           \
  ENTRY(GL_HALF_FLOAT)                                                 \
  ENTRY(GL_MAP_INVALIDATE_BUFFER_BIT)                                  \
  ENTRY(GL_MAP_FLUSH_EXPLICIT_BIT)                                     \
  ENTRY(GL_MAP_UNSYNCHRONIZED_BIT)                                     \
  ENTRY(GL_COMPRESSED_RED_RGTC1)                                       \
  ENTRY(GL_COMPRESSED_SIGNED_RED_RGTC1)                                \
  ENTRY(GL_COMPRESSED_RG_RGTC2)                                        \
  ENTRY(GL_COMPRESSED_SIGNED_RG_RGTC2)                                 \
  ENTRY(GL_RG)                                                         \
  ENTRY(GL_RG_INTEGER)                                                 \
  ENTRY(GL_R8)                                                         \
  ENTRY(GL_R16)                                                        \
  ENTRY(GL_RG8)                                                        \
  ENTRY(GL_RG16)                                                       \
  ENTRY(GL_R16F)                                                       \
  ENTRY(GL_R32F)                                                       \
  ENTRY(GL_RG16F)                                                      \
  ENTRY(GL_RG32F)                                                      \
  ENTRY(GL_R8I)                                                        \
  ENTRY(GL_R8UI)                                                       \
  ENTRY(GL_R16I)                                                       \
  ENTRY(GL_R16UI)                                                      \
  ENTRY(GL_R32I)                                                       \
  ENTRY(GL_R32UI)                                                      \
  ENTRY(GL_RG8I)                                                       \
  ENTRY(GL_RG8UI)                                                      \
  ENTRY(GL_RG16I)                                                      \
  ENTRY(GL_RG16UI)                                                     \
  ENTRY(GL_RG32I)                                                      \
  ENTRY(GL_RG32UI)                                                     \
  ENTRY(GL_VERTEX_ARRAY_BINDING)                                       \
  ENTRY(GL_SAMPLER_2D_RECT)                                            \
  ENTRY(GL_SAMPLER_2D_RECT_SHADOW)                                     \
  ENTRY(GL_SAMPLER_BUFFER)                                             \
  ENTRY(GL_INT_SAMPLER_2D_RECT)                                        \
  ENTRY(GL_INT_SAMPLER_BUFFER)                                         \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_2D_RECT)                               \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_BUFFER)                                \
  ENTRY(GL_TEXTURE_BUFFER)                                             \
  ENTRY(GL_MAX_TEXTURE_BUFFER_SIZE)                                    \
  ENTRY(GL_TEXTURE_BINDING_BUFFER)                                     \
  ENTRY(GL_TEXTURE_BUFFER_DATA_STORE_BINDING)                          \
  ENTRY(GL_TEXTURE_RECTANGLE)                                          \
  ENTRY(GL_TEXTURE_BINDING_RECTANGLE)                                  \
  ENTRY(GL_PROXY_TEXTURE_RECTANGLE)                                    \
  ENTRY(GL_MAX_RECTANGLE_TEXTURE_SIZE)                                 \
  ENTRY(GL_R8_SNORM)                                                   \
  ENTRY(GL_RG8_SNORM)                                                  \
  ENTRY(GL_RGB8_SNORM)                                                 \
  ENTRY(GL_RGBA8_SNORM)                                                \
  ENTRY(GL_R16_SNORM)                                                  \
  ENTRY(GL_RG16_SNORM)                                                 \
  ENTRY(GL_RGB16_SNORM)                                                \
  ENTRY(GL_RGBA16_SNORM)                                               \
  ENTRY(GL_SIGNED_NORMALIZED)                                          \
  ENTRY(GL_PRIMITIVE_RESTART)                                          \
  ENTRY(GL_PRIMITIVE_RESTART_INDEX)                                    \
  ENTRY(GL_COPY_READ_BUFFER)                                           \
  ENTRY(GL_COPY_WRITE_BUFFER)                                          \
  ENTRY(GL_UNIFORM_BUFFER)                                             \
  ENTRY(GL_UNIFORM_BUFFER_BINDING)                                     \
  ENTRY(GL_UNIFORM_BUFFER_START)                                       \
  ENTRY(GL_UNIFORM_BUFFER_SIZE)                                        \
  ENTRY(GL_MAX_VERTEX_UNIFORM_BLOCKS)                                  \
  ENTRY(GL_MAX_GEOMETRY_UNIFORM_BLOCKS)                                \
  ENTRY(GL_MAX_FRAGMENT_UNIFORM_BLOCKS)                                \
  ENTRY(GL_MAX_COMBINED_UNIFORM_BLOCKS)                                \
  ENTRY(GL_MAX_UNIFORM_BUFFER_BINDINGS)                                \
  ENTRY(GL_MAX_UNIFORM_BLOCK_SIZE)                                     \
  ENTRY(GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS)                     \
  ENTRY(GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS)                   \
  ENTRY(GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS)                   \
  ENTRY(GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT)                            \
  ENTRY(GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH)                       \
  ENTRY(GL_ACTIVE_UNIFORM_BLOCKS)                                      \
  ENTRY(GL_UNIFORM_TYPE)                                               \
  ENTRY(GL_UNIFORM_SIZE)                                               \
  ENTRY(GL_UNIFORM_NAME_LENGTH)                                        \
  ENTRY(GL_UNIFORM_BLOCK_INDEX)                                        \
  ENTRY(GL_UNIFORM_OFFSET)                                             \
  ENTRY(GL_UNIFORM_ARRAY_STRIDE)                                       \
  ENTRY(GL_UNIFORM_MATRIX_STRIDE)                                      \
  ENTRY(GL_UNIFORM_IS_ROW_MAJOR)                                       \
  ENTRY(GL_UNIFORM_BLOCK_BINDING)                                      \
  ENTRY(GL_UNIFORM_BLOCK_DATA_SIZE)                                    \
  ENTRY(GL_UNIFORM_BLOCK_NAME_LENGTH)                                  \
  ENTRY(GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS)                              \
  ENTRY(GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES)                       \
  ENTRY(GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER)                  \
  ENTRY(GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER)                \
  ENTRY(GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER)                \
  ENTRY(GL_INVALID_INDEX)                                              \
  ENTRY(GL_LINES_ADJACENCY)                                            \
  ENTRY(GL_LINE_STRIP_ADJACENCY)                                       \
  ENTRY(GL_TRIANGLES_ADJACENCY)                                        \
  ENTRY(GL_TRIANGLE_STRIP_ADJACENCY)                                   \
  ENTRY(GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS)                           \
  ENTRY(GL_FRAMEBUFFER_ATTACHMENT_LAYERED)                             \
  ENTRY(GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS)                       \
  ENTRY(GL_GEOMETRY_SHADER)                                            \
  ENTRY(GL_GEOMETRY_VERTICES_OUT)                                      \
  ENTRY(GL_GEOMETRY_INPUT_TYPE)                                        \
  ENTRY(GL_GEOMETRY_OUTPUT_TYPE)                                       \
  ENTRY(GL_MAX_GEOMETRY_UNIFORM_COMPONENTS)                            \
  ENTRY(GL_MAX_GEOMETRY_OUTPUT_VERTICES)                               \
  ENTRY(GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS)                       \
  ENTRY(GL_MAX_VERTEX_OUTPUT_COMPONENTS)                               \
  ENTRY(GL_MAX_GEOMETRY_INPUT_COMPONENTS)                              \
  ENTRY(GL_MAX_GEOMETRY_OUTPUT_COMPONENTS)                             \
  ENTRY(GL_MAX_FRAGMENT_INPUT_COMPONENTS)                              \
  ENTRY(GL_CONTEXT_PROFILE_MASK)                                       \
  ENTRY(GL_DEPTH_CLAMP)                                                \
  ENTRY(GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION)                   \
  ENTRY(GL_FIRST_VERTEX_CONVENTION)                                    \
  ENTRY(GL_LAST_VERTEX_CONVENTION)                                     \
  ENTRY(GL_PROVOKING_VERTEX)                                           \
  ENTRY(GL_TEXTURE_CUBE_MAP_SEAMLESS)                                  \
  ENTRY(GL_MAX_SERVER_WAIT_TIMEOUT)                                    \
  ENTRY(GL_OBJECT_TYPE)                                                \
  ENTRY(GL_SYNC_CONDITION)                                             \
  ENTRY(GL_SYNC_STATUS)                                                \
  ENTRY(GL_SYNC_FLAGS)                                                 \
  ENTRY(GL_SYNC_FENCE)                                                 \
  ENTRY(GL_SYNC_GPU_COMMANDS_COMPLETE)                                 \
  ENTRY(GL_UNSIGNALED)                                                 \
  ENTRY(GL_SIGNALED)                                                   \
  ENTRY(GL_ALREADY_SIGNALED)                                           \
  ENTRY(GL_TIMEOUT_EXPIRED)                                            \
  ENTRY(GL_CONDITION_SATISFIED)                                        \
  ENTRY(GL_WAIT_FAILED)                                                \
  ENTRY(GL_SAMPLE_POSITION)                                            \
  ENTRY(GL_SAMPLE_MASK)                                                \
  ENTRY(GL_SAMPLE_MASK_VALUE)                                          \
  ENTRY(GL_MAX_SAMPLE_MASK_WORDS)                                      \
  ENTRY(GL_TEXTURE_2D_MULTISAMPLE)                                     \
  ENTRY(GL_PROXY_TEXTURE_2D_MULTISAMPLE)                               \
  ENTRY(GL_TEXTURE_2D_MULTISAMPLE_ARRAY)                               \
  ENTRY(GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY)                         \
  ENTRY(GL_TEXTURE_BINDING_2D_MULTISAMPLE)                             \
  ENTRY(GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY)                       \
  ENTRY(GL_TEXTURE_SAMPLES)                                            \
  ENTRY(GL_TEXTURE_FIXED_SAMPLE_LOCATIONS)                             \
  ENTRY(GL_SAMPLER_2D_MULTISAMPLE)                                     \
  ENTRY(GL_INT_SAMPLER_2D_MULTISAMPLE)                                 \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE)                        \
  ENTRY(GL_SAMPLER_2D_MULTISAMPLE_ARRAY)                               \
  ENTRY(GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY)                           \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY)                  \
  ENTRY(GL_MAX_COLOR_TEXTURE_SAMPLES)                                  \
  ENTRY(GL_MAX_DEPTH_TEXTURE_SAMPLES)                                  \
  ENTRY(GL_MAX_INTEGER_SAMPLES)                                        \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_DIVISOR)                                \
  ENTRY(GL_SRC1_COLOR)                                                 \
  ENTRY(GL_ONE_MINUS_SRC1_COLOR)                                       \
  ENTRY(GL_ONE_MINUS_SRC1_ALPHA)                                       \
  ENTRY(GL_MAX_DUAL_SOURCE_DRAW_BUFFERS)                               \
  ENTRY(GL_ANY_SAMPLES_PASSED)                                         \
  ENTRY(GL_SAMPLER_BINDING)                                            \
  ENTRY(GL_RGB10_A2UI)                                                 \
  ENTRY(GL_TEXTURE_SWIZZLE_R)                                          \
  ENTRY(GL_TEXTURE_SWIZZLE_G)                                          \
  ENTRY(GL_TEXTURE_SWIZZLE_B)                                          \
  ENTRY(GL_TEXTURE_SWIZZLE_A)                                          \
  ENTRY(GL_TEXTURE_SWIZZLE_RGBA)                                       \
  ENTRY(GL_TIME_ELAPSED)                                               \
  ENTRY(GL_TIMESTAMP)                                                  \
  ENTRY(GL_INT_2_10_10_10_REV)                                         \
  ENTRY(GL_SAMPLE_SHADING)                                             \
  ENTRY(GL_MIN_SAMPLE_SHADING_VALUE)                                   \
  ENTRY(GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET)                          \
  ENTRY(GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET)                          \
  ENTRY(GL_TEXTURE_CUBE_MAP_ARRAY)                                     \
  ENTRY(GL_TEXTURE_BINDING_CUBE_MAP_ARRAY)                             \
  ENTRY(GL_PROXY_TEXTURE_CUBE_MAP_ARRAY)                               \
  ENTRY(GL_SAMPLER_CUBE_MAP_ARRAY)                                     \
  ENTRY(GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW)                              \
  ENTRY(GL_INT_SAMPLER_CUBE_MAP_ARRAY)                                 \
  ENTRY(GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY)                        \
  ENTRY(GL_DRAW_INDIRECT_BUFFER)                                       \
  ENTRY(GL_DRAW_INDIRECT_BUFFER_BINDING)                               \
  ENTRY(GL_GEOMETRY_SHADER_INVOCATIONS)                                \
  ENTRY(GL_MAX_GEOMETRY_SHADER_INVOCATIONS)                            \
  ENTRY(GL_MIN_FRAGMENT_INTERPOLATION_OFFSET)                          \
  ENTRY(GL_MAX_FRAGMENT_INTERPOLATION_OFFSET)                          \
  ENTRY(GL_FRAGMENT_INTERPOLATION_OFFSET_BITS)                         \
  ENTRY(GL_MAX_VERTEX_STREAMS)                                         \
  ENTRY(GL_DOUBLE_VEC2)                                                \
  ENTRY(GL_DOUBLE_VEC3)                                                \
  ENTRY(GL_DOUBLE_VEC4)                                                \
  ENTRY(GL_DOUBLE_MAT2)                                                \
  ENTRY(GL_DOUBLE_MAT3)                                                \
  ENTRY(GL_DOUBLE_MAT4)                                                \
  ENTRY(GL_DOUBLE_MAT2x3)                                              \
  ENTRY(GL_DOUBLE_MAT2x4)                                              \
  ENTRY(GL_DOUBLE_MAT3x2)                                              \
  ENTRY(GL_DOUBLE_MAT3x4)                                              \
  ENTRY(GL_DOUBLE_MAT4x2)                                              \
  ENTRY(GL_DOUBLE_MAT4x3)                                              \
  ENTRY(GL_ACTIVE_SUBROUTINES)                                         \
  ENTRY(GL_ACTIVE_SUBROUTINE_UNIFORMS)                                 \
  ENTRY(GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS)                        \
  ENTRY(GL_ACTIVE_SUBROUTINE_MAX_LENGTH)                               \
  ENTRY(GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH)                       \
  ENTRY(GL_MAX_SUBROUTINES)                                            \
  ENTRY(GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS)                           \
  ENTRY(GL_NUM_COMPATIBLE_SUBROUTINES)                                 \
  ENTRY(GL_COMPATIBLE_SUBROUTINES)                                     \
  ENTRY(GL_PATCHES)                                                    \
  ENTRY(GL_PATCH_VERTICES)                                             \
  ENTRY(GL_PATCH_DEFAULT_INNER_LEVEL)                                  \
  ENTRY(GL_PATCH_DEFAULT_OUTER_LEVEL)                                  \
  ENTRY(GL_TESS_CONTROL_OUTPUT_VERTICES)                               \
  ENTRY(GL_TESS_GEN_MODE)                                              \
  ENTRY(GL_TESS_GEN_SPACING)                                           \
  ENTRY(GL_TESS_GEN_VERTEX_ORDER)                                      \
  ENTRY(GL_TESS_GEN_POINT_MODE)                                        \
  ENTRY(GL_ISOLINES)                                                   \
  ENTRY(GL_QUADS)                                                      \
  ENTRY(GL_FRACTIONAL_ODD)                                             \
  ENTRY(GL_FRACTIONAL_EVEN)                                            \
  ENTRY(GL_MAX_PATCH_VERTICES)                                         \
  ENTRY(GL_MAX_TESS_GEN_LEVEL)                                         \
  ENTRY(GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS)                        \
  ENTRY(GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS)                     \
  ENTRY(GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS)                       \
  ENTRY(GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS)                    \
  ENTRY(GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS)                         \
  ENTRY(GL_MAX_TESS_PATCH_COMPONENTS)                                  \
  ENTRY(GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS)                   \
  ENTRY(GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS)                      \
  ENTRY(GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS)                            \
  ENTRY(GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS)                         \
  ENTRY(GL_MAX_TESS_CONTROL_INPUT_COMPONENTS)                          \
  ENTRY(GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS)                       \
  ENTRY(GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS)               \
  ENTRY(GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS)            \
  ENTRY(GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER)            \
  ENTRY(GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER)         \
  ENTRY(GL_TESS_EVALUATION_SHADER)                                     \
  ENTRY(GL_TESS_CONTROL_SHADER)                                        \
  ENTRY(GL_TRANSFORM_FEEDBACK)                                         \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED)                           \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE)                           \
  ENTRY(GL_TRANSFORM_FEEDBACK_BINDING)                                 \
  ENTRY(GL_MAX_TRANSFORM_FEEDBACK_BUFFERS)                             \
  ENTRY(GL_FIXED)                                                      \
  ENTRY(GL_IMPLEMENTATION_COLOR_READ_TYPE)                             \
  ENTRY(GL_IMPLEMENTATION_COLOR_READ_FORMAT)                           \
  ENTRY(GL_LOW_FLOAT)                                                  \
  ENTRY(GL_MEDIUM_FLOAT)                                               \
  ENTRY(GL_HIGH_FLOAT)                                                 \
  ENTRY(GL_LOW_INT)                                                    \
  ENTRY(GL_MEDIUM_INT)                                                 \
  ENTRY(GL_HIGH_INT)                                                   \
  ENTRY(GL_SHADER_COMPILER)                                            \
  ENTRY(GL_SHADER_BINARY_FORMATS)                                      \
  ENTRY(GL_NUM_SHADER_BINARY_FORMATS)                                  \
  ENTRY(GL_MAX_VERTEX_UNIFORM_VECTORS)                                 \
  ENTRY(GL_MAX_VARYING_VECTORS)                                        \
  ENTRY(GL_MAX_FRAGMENT_UNIFORM_VECTORS)                               \
  ENTRY(GL_RGB565)                                                     \
  ENTRY(GL_PROGRAM_BINARY_RETRIEVABLE_HINT)                            \
  ENTRY(GL_PROGRAM_BINARY_LENGTH)                                      \
  ENTRY(GL_NUM_PROGRAM_BINARY_FORMATS)                                 \
  ENTRY(GL_PROGRAM_BINARY_FORMATS)                                     \
  ENTRY(GL_PROGRAM_SEPARABLE)                                          \
  ENTRY(GL_ACTIVE_PROGRAM)                                             \
  ENTRY(GL_PROGRAM_PIPELINE_BINDING)                                   \
  ENTRY(GL_MAX_VIEWPORTS)                                              \
  ENTRY(GL_VIEWPORT_SUBPIXEL_BITS)                                     \
  ENTRY(GL_VIEWPORT_BOUNDS_RANGE)                                      \
  ENTRY(GL_LAYER_PROVOKING_VERTEX)                                     \
  ENTRY(GL_VIEWPORT_INDEX_PROVOKING_VERTEX)                            \
  ENTRY(GL_UNDEFINED_VERTEX)                                           \
  ENTRY(GL_UNPACK_COMPRESSED_BLOCK_WIDTH)                              \
  ENTRY(GL_UNPACK_COMPRESSED_BLOCK_HEIGHT)                             \
  ENTRY(GL_UNPACK_COMPRESSED_BLOCK_DEPTH)                              \
  ENTRY(GL_UNPACK_COMPRESSED_BLOCK_SIZE)                               \
  ENTRY(GL_PACK_COMPRESSED_BLOCK_WIDTH)                                \
  ENTRY(GL_PACK_COMPRESSED_BLOCK_HEIGHT)                               \
  ENTRY(GL_PACK_COMPRESSED_BLOCK_DEPTH)                                \
  ENTRY(GL_PACK_COMPRESSED_BLOCK_SIZE)                                 \
  ENTRY(GL_NUM_SAMPLE_COUNTS)                                          \
  ENTRY(GL_MIN_MAP_BUFFER_ALIGNMENT)                                   \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER)                                      \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_BINDING)                              \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_START)                                \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_SIZE)                                 \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE)                            \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS)               \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES)        \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER)          \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER)    \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER) \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER)        \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER)        \
  ENTRY(GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS)                          \
  ENTRY(GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS)                    \
  ENTRY(GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS)                 \
  ENTRY(GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS)                        \
  ENTRY(GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS)                        \
  ENTRY(GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS)                        \
  ENTRY(GL_MAX_VERTEX_ATOMIC_COUNTERS)                                 \
  ENTRY(GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS)                           \
  ENTRY(GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS)                        \
  ENTRY(GL_MAX_GEOMETRY_ATOMIC_COUNTERS)                               \
  ENTRY(GL_MAX_FRAGMENT_ATOMIC_COUNTERS)                               \
  ENTRY(GL_MAX_COMBINED_ATOMIC_COUNTERS)                               \
  ENTRY(GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE)                             \
  ENTRY(GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS)                         \
  ENTRY(GL_ACTIVE_ATOMIC_COUNTER_BUFFERS)                              \
  ENTRY(GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX)                        \
  ENTRY(GL_UNSIGNED_INT_ATOMIC_COUNTER)                                \
  ENTRY(GL_COMMAND_BARRIER_BIT)                                        \
  ENTRY(GL_PIXEL_BUFFER_BARRIER_BIT)                                   \
  ENTRY(GL_TRANSFORM_FEEDBACK_BARRIER_BIT)                             \
  ENTRY(GL_MAX_IMAGE_UNITS)                                            \
  ENTRY(GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS)              \
  ENTRY(GL_IMAGE_BINDING_NAME)                                         \
  ENTRY(GL_IMAGE_BINDING_LEVEL)                                        \
  ENTRY(GL_IMAGE_BINDING_LAYERED)                                      \
  ENTRY(GL_IMAGE_BINDING_LAYER)                                        \
  ENTRY(GL_IMAGE_BINDING_ACCESS)                                       \
  ENTRY(GL_IMAGE_1D)                                                   \
  ENTRY(GL_IMAGE_2D)                                                   \
  ENTRY(GL_IMAGE_3D)                                                   \
  ENTRY(GL_IMAGE_2D_RECT)                                              \
  ENTRY(GL_IMAGE_CUBE)                                                 \
  ENTRY(GL_IMAGE_BUFFER)                                               \
  ENTRY(GL_IMAGE_1D_ARRAY)                                             \
  ENTRY(GL_IMAGE_2D_ARRAY)                                             \
  ENTRY(GL_IMAGE_CUBE_MAP_ARRAY)                                       \
  ENTRY(GL_IMAGE_2D_MULTISAMPLE)                                       \
  ENTRY(GL_IMAGE_2D_MULTISAMPLE_ARRAY)                                 \
  ENTRY(GL_INT_IMAGE_1D)                                               \
  ENTRY(GL_INT_IMAGE_2D)                                               \
  ENTRY(GL_INT_IMAGE_3D)                                               \
  ENTRY(GL_INT_IMAGE_2D_RECT)                                          \
  ENTRY(GL_INT_IMAGE_CUBE)                                             \
  ENTRY(GL_INT_IMAGE_BUFFER)                                           \
  ENTRY(GL_INT_IMAGE_1D_ARRAY)                                         \
  ENTRY(GL_INT_IMAGE_2D_ARRAY)                                         \
  ENTRY(GL_INT_IMAGE_CUBE_MAP_ARRAY)                                   \
  ENTRY(GL_INT_IMAGE_2D_MULTISAMPLE)                                   \
  ENTRY(GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY)                             \
  ENTRY(GL_UNSIGNED_INT_IMAGE_1D)                                      \
  ENTRY(GL_UNSIGNED_INT_IMAGE_2D)                                      \
  ENTRY(GL_UNSIGNED_INT_IMAGE_3D)                                      \
  ENTRY(GL_UNSIGNED_INT_IMAGE_2D_RECT)                                 \
  ENTRY(GL_UNSIGNED_INT_IMAGE_CUBE)                                    \
  ENTRY(GL_UNSIGNED_INT_IMAGE_BUFFER)                                  \
  ENTRY(GL_UNSIGNED_INT_IMAGE_1D_ARRAY)                                \
  ENTRY(GL_UNSIGNED_INT_IMAGE_2D_ARRAY)                                \
  ENTRY(GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY)                          \
  ENTRY(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE)                          \
  ENTRY(GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY)                    \
  ENTRY(GL_MAX_IMAGE_SAMPLES)                                          \
  ENTRY(GL_IMAGE_BINDING_FORMAT)                                       \
  ENTRY(GL_IMAGE_FORMAT_COMPATIBILITY_TYPE)                            \
  ENTRY(GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE)                         \
  ENTRY(GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS)                        \
  ENTRY(GL_MAX_VERTEX_IMAGE_UNIFORMS)                                  \
  ENTRY(GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS)                            \
  ENTRY(GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS)                         \
  ENTRY(GL_MAX_GEOMETRY_IMAGE_UNIFORMS)                                \
  ENTRY(GL_MAX_FRAGMENT_IMAGE_UNIFORMS)                                \
  ENTRY(GL_MAX_COMBINED_IMAGE_UNIFORMS)                                \
  ENTRY(GL_COMPRESSED_RGBA_BPTC_UNORM)                                 \
  ENTRY(GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM)                           \
  ENTRY(GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT)                           \
  ENTRY(GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT)                         \
  ENTRY(GL_TEXTURE_IMMUTABLE_FORMAT)                                   \
  ENTRY(GL_NUM_SHADING_LANGUAGE_VERSIONS)                              \
  ENTRY(GL_VERTEX_ATTRIB_ARRAY_LONG)                                   \
  ENTRY(GL_COMPRESSED_RGB8_ETC2)                                       \
  ENTRY(GL_COMPRESSED_SRGB8_ETC2)                                      \
  ENTRY(GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2)                   \
  ENTRY(GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2)                  \
  ENTRY(GL_COMPRESSED_RGBA8_ETC2_EAC)                                  \
  ENTRY(GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC)                           \
  ENTRY(GL_COMPRESSED_R11_EAC)                                         \
  ENTRY(GL_COMPRESSED_SIGNED_R11_EAC)                                  \
  ENTRY(GL_COMPRESSED_RG11_EAC)                                        \
  ENTRY(GL_COMPRESSED_SIGNED_RG11_EAC)                                 \
  ENTRY(GL_PRIMITIVE_RESTART_FIXED_INDEX)                              \
  ENTRY(GL_ANY_SAMPLES_PASSED_CONSERVATIVE)                            \
  ENTRY(GL_MAX_ELEMENT_INDEX)                                          \
  ENTRY(GL_COMPUTE_SHADER)                                             \
  ENTRY(GL_MAX_COMPUTE_UNIFORM_BLOCKS)                                 \
  ENTRY(GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS)                            \
  ENTRY(GL_MAX_COMPUTE_IMAGE_UNIFORMS)                                 \
  ENTRY(GL_MAX_COMPUTE_SHARED_MEMORY_SIZE)                             \
  ENTRY(GL_MAX_COMPUTE_UNIFORM_COMPONENTS)                             \
  ENTRY(GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS)                         \
  ENTRY(GL_MAX_COMPUTE_ATOMIC_COUNTERS)                                \
  ENTRY(GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS)                    \
  ENTRY(GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS)                         \
  ENTRY(GL_MAX_COMPUTE_WORK_GROUP_COUNT)                               \
  ENTRY(GL_MAX_COMPUTE_WORK_GROUP_SIZE)                                \
  ENTRY(GL_COMPUTE_WORK_GROUP_SIZE)                                    \
  ENTRY(GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER)                 \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER)         \
  ENTRY(GL_DISPATCH_INDIRECT_BUFFER)                                   \
  ENTRY(GL_DISPATCH_INDIRECT_BUFFER_BINDING)                           \
  ENTRY(GL_DEBUG_OUTPUT_SYNCHRONOUS)                                   \
  ENTRY(GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH)                           \
  ENTRY(GL_DEBUG_CALLBACK_FUNCTION)                                    \
  ENTRY(GL_DEBUG_CALLBACK_USER_PARAM)                                  \
  ENTRY(GL_DEBUG_SOURCE_API)                                           \
  ENTRY(GL_DEBUG_SOURCE_WINDOW_SYSTEM)                                 \
  ENTRY(GL_DEBUG_SOURCE_SHADER_COMPILER)                               \
  ENTRY(GL_DEBUG_SOURCE_THIRD_PARTY)                                   \
  ENTRY(GL_DEBUG_SOURCE_APPLICATION)                                   \
  ENTRY(GL_DEBUG_SOURCE_OTHER)                                         \
  ENTRY(GL_DEBUG_TYPE_ERROR)                                           \
  ENTRY(GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR)                             \
  ENTRY(GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR)                              \
  ENTRY(GL_DEBUG_TYPE_PORTABILITY)                                     \
  ENTRY(GL_DEBUG_TYPE_PERFORMANCE)                                     \
  ENTRY(GL_DEBUG_TYPE_OTHER)                                           \
  ENTRY(GL_MAX_DEBUG_MESSAGE_LENGTH)                                   \
  ENTRY(GL_MAX_DEBUG_LOGGED_MESSAGES)                                  \
  ENTRY(GL_DEBUG_LOGGED_MESSAGES)                                      \
  ENTRY(GL_DEBUG_SEVERITY_HIGH)                                        \
  ENTRY(GL_DEBUG_SEVERITY_MEDIUM)                                      \
  ENTRY(GL_DEBUG_SEVERITY_LOW)                                         \
  ENTRY(GL_DEBUG_TYPE_MARKER)                                          \
  ENTRY(GL_DEBUG_TYPE_PUSH_GROUP)                                      \
  ENTRY(GL_DEBUG_TYPE_POP_GROUP)                                       \
  ENTRY(GL_DEBUG_SEVERITY_NOTIFICATION)                                \
  ENTRY(GL_MAX_DEBUG_GROUP_STACK_DEPTH)                                \
  ENTRY(GL_DEBUG_GROUP_STACK_DEPTH)                                    \
  ENTRY(GL_BUFFER)                                                     \
  ENTRY(GL_SHADER)                                                     \
  ENTRY(GL_PROGRAM)                                                    \
  ENTRY(GL_VERTEX_ARRAY)                                               \
  ENTRY(GL_QUERY)                                                      \
  ENTRY(GL_PROGRAM_PIPELINE)                                           \
  ENTRY(GL_SAMPLER)                                                    \
  ENTRY(GL_MAX_LABEL_LENGTH)                                           \
  ENTRY(GL_DEBUG_OUTPUT)                                               \
  ENTRY(GL_MAX_UNIFORM_LOCATIONS)                                      \
  ENTRY(GL_FRAMEBUFFER_DEFAULT_WIDTH)                                  \
  ENTRY(GL_FRAMEBUFFER_DEFAULT_HEIGHT)                                 \
  ENTRY(GL_FRAMEBUFFER_DEFAULT_LAYERS)                                 \
  ENTRY(GL_FRAMEBUFFER_DEFAULT_SAMPLES)                                \
  ENTRY(GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS)                 \
  ENTRY(GL_MAX_FRAMEBUFFER_WIDTH)                                      \
  ENTRY(GL_MAX_FRAMEBUFFER_HEIGHT)                                     \
  ENTRY(GL_MAX_FRAMEBUFFER_LAYERS)                                     \
  ENTRY(GL_MAX_FRAMEBUFFER_SAMPLES)                                    \
  ENTRY(GL_INTERNALFORMAT_SUPPORTED)                                   \
  ENTRY(GL_INTERNALFORMAT_PREFERRED)                                   \
  ENTRY(GL_INTERNALFORMAT_RED_SIZE)                                    \
  ENTRY(GL_INTERNALFORMAT_GREEN_SIZE)                                  \
  ENTRY(GL_INTERNALFORMAT_BLUE_SIZE)                                   \
  ENTRY(GL_INTERNALFORMAT_ALPHA_SIZE)                                  \
  ENTRY(GL_INTERNALFORMAT_DEPTH_SIZE)                                  \
  ENTRY(GL_INTERNALFORMAT_STENCIL_SIZE)                                \
  ENTRY(GL_INTERNALFORMAT_SHARED_SIZE)                                 \
  ENTRY(GL_INTERNALFORMAT_RED_TYPE)                                    \
  ENTRY(GL_INTERNALFORMAT_GREEN_TYPE)                                  \
  ENTRY(GL_INTERNALFORMAT_BLUE_TYPE)                                   \
  ENTRY(GL_INTERNALFORMAT_ALPHA_TYPE)                                  \
  ENTRY(GL_INTERNALFORMAT_DEPTH_TYPE)                                  \
  ENTRY(GL_INTERNALFORMAT_STENCIL_TYPE)                                \
  ENTRY(GL_MAX_WIDTH)                                                  \
  ENTRY(GL_MAX_HEIGHT)                                                 \
  ENTRY(GL_MAX_DEPTH)                                                  \
  ENTRY(GL_MAX_LAYERS)                                                 \
  ENTRY(GL_MAX_COMBINED_DIMENSIONS)                                    \
  ENTRY(GL_COLOR_COMPONENTS)                                           \
  ENTRY(GL_DEPTH_COMPONENTS)                                           \
  ENTRY(GL_STENCIL_COMPONENTS)                                         \
  ENTRY(GL_COLOR_RENDERABLE)                                           \
  ENTRY(GL_DEPTH_RENDERABLE)                                           \
  ENTRY(GL_STENCIL_RENDERABLE)                                         \
  ENTRY(GL_FRAMEBUFFER_RENDERABLE)                                     \
  ENTRY(GL_FRAMEBUFFER_RENDERABLE_LAYERED)                             \
  ENTRY(GL_FRAMEBUFFER_BLEND)                                          \
  ENTRY(GL_READ_PIXELS)                                                \
  ENTRY(GL_READ_PIXELS_FORMAT)                                         \
  ENTRY(GL_READ_PIXELS_TYPE)                                           \
  ENTRY(GL_TEXTURE_IMAGE_FORMAT)                                       \
  ENTRY(GL_TEXTURE_IMAGE_TYPE)                                         \
  ENTRY(GL_GET_TEXTURE_IMAGE_FORMAT)                                   \
  ENTRY(GL_GET_TEXTURE_IMAGE_TYPE)                                     \
  ENTRY(GL_MIPMAP)                                                     \
  ENTRY(GL_MANUAL_GENERATE_MIPMAP)                                     \
  ENTRY(GL_AUTO_GENERATE_MIPMAP)                                       \
  ENTRY(GL_COLOR_ENCODING)                                             \
  ENTRY(GL_SRGB_READ)                                                  \
  ENTRY(GL_SRGB_WRITE)                                                 \
  ENTRY(GL_FILTER)                                                     \
  ENTRY(GL_VERTEX_TEXTURE)                                             \
  ENTRY(GL_TESS_CONTROL_TEXTURE)                                       \
  ENTRY(GL_TESS_EVALUATION_TEXTURE)                                    \
  ENTRY(GL_GEOMETRY_TEXTURE)                                           \
  ENTRY(GL_FRAGMENT_TEXTURE)                                           \
  ENTRY(GL_COMPUTE_TEXTURE)                                            \
  ENTRY(GL_TEXTURE_SHADOW)                                             \
  ENTRY(GL_TEXTURE_GATHER)                                             \
  ENTRY(GL_TEXTURE_GATHER_SHADOW)                                      \
  ENTRY(GL_SHADER_IMAGE_LOAD)                                          \
  ENTRY(GL_SHADER_IMAGE_STORE)                                         \
  ENTRY(GL_SHADER_IMAGE_ATOMIC)                                        \
  ENTRY(GL_IMAGE_TEXEL_SIZE)                                           \
  ENTRY(GL_IMAGE_COMPATIBILITY_CLASS)                                  \
  ENTRY(GL_IMAGE_PIXEL_FORMAT)                                         \
  ENTRY(GL_IMAGE_PIXEL_TYPE)                                           \
  ENTRY(GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST)                        \
  ENTRY(GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST)                      \
  ENTRY(GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE)                       \
  ENTRY(GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE)                     \
  ENTRY(GL_TEXTURE_COMPRESSED_BLOCK_WIDTH)                             \
  ENTRY(GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT)                            \
  ENTRY(GL_TEXTURE_COMPRESSED_BLOCK_SIZE)                              \
  ENTRY(GL_CLEAR_BUFFER)                                               \
  ENTRY(GL_TEXTURE_VIEW)                                               \
  ENTRY(GL_VIEW_COMPATIBILITY_CLASS)                                   \
  ENTRY(GL_FULL_SUPPORT)                                               \
  ENTRY(GL_CAVEAT_SUPPORT)                                             \
  ENTRY(GL_IMAGE_CLASS_4_X_32)                                         \
  ENTRY(GL_IMAGE_CLASS_2_X_32)                                         \
  ENTRY(GL_IMAGE_CLASS_1_X_32)                                         \
  ENTRY(GL_IMAGE_CLASS_4_X_16)                                         \
  ENTRY(GL_IMAGE_CLASS_2_X_16)                                         \
  ENTRY(GL_IMAGE_CLASS_1_X_16)                                         \
  ENTRY(GL_IMAGE_CLASS_4_X_8)                                          \
  ENTRY(GL_IMAGE_CLASS_2_X_8)                                          \
  ENTRY(GL_IMAGE_CLASS_1_X_8)                                          \
  ENTRY(GL_IMAGE_CLASS_11_11_10)                                       \
  ENTRY(GL_IMAGE_CLASS_10_10_10_2)                                     \
  ENTRY(GL_VIEW_CLASS_128_BITS)                                        \
  ENTRY(GL_VIEW_CLASS_96_BITS)                                         \
  ENTRY(GL_VIEW_CLASS_64_BITS)                                         \
  ENTRY(GL_VIEW_CLASS_48_BITS)                                         \
  ENTRY(GL_VIEW_CLASS_32_BITS)                                         \
  ENTRY(GL_VIEW_CLASS_24_BITS)                                         \
  ENTRY(GL_VIEW_CLASS_16_BITS)                                         \
  ENTRY(GL_VIEW_CLASS_8_BITS)                                          \
  ENTRY(GL_VIEW_CLASS_S3TC_DXT1_RGB)                                   \
  ENTRY(GL_VIEW_CLASS_S3TC_DXT1_RGBA)                                  \
  ENTRY(GL_VIEW_CLASS_S3TC_DXT3_RGBA)                                  \
  ENTRY(GL_VIEW_CLASS_S3TC_DXT5_RGBA)                                  \
  ENTRY(GL_VIEW_CLASS_RGTC1_RED)                                       \
  ENTRY(GL_VIEW_CLASS_RGTC2_RG)                                        \
  ENTRY(GL_VIEW_CLASS_BPTC_UNORM)                                      \
  ENTRY(GL_VIEW_CLASS_BPTC_FLOAT)                                      \
  ENTRY(GL_UNIFORM)                                                    \
  ENTRY(GL_UNIFORM_BLOCK)                                              \
  ENTRY(GL_PROGRAM_INPUT)                                              \
  ENTRY(GL_PROGRAM_OUTPUT)                                             \
  ENTRY(GL_BUFFER_VARIABLE)                                            \
  ENTRY(GL_SHADER_STORAGE_BLOCK)                                       \
  ENTRY(GL_VERTEX_SUBROUTINE)                                          \
  ENTRY(GL_TESS_CONTROL_SUBROUTINE)                                    \
  ENTRY(GL_TESS_EVALUATION_SUBROUTINE)                                 \
  ENTRY(GL_GEOMETRY_SUBROUTINE)                                        \
  ENTRY(GL_FRAGMENT_SUBROUTINE)                                        \
  ENTRY(GL_COMPUTE_SUBROUTINE)                                         \
  ENTRY(GL_VERTEX_SUBROUTINE_UNIFORM)                                  \
  ENTRY(GL_TESS_CONTROL_SUBROUTINE_UNIFORM)                            \
  ENTRY(GL_TESS_EVALUATION_SUBROUTINE_UNIFORM)                         \
  ENTRY(GL_GEOMETRY_SUBROUTINE_UNIFORM)                                \
  ENTRY(GL_FRAGMENT_SUBROUTINE_UNIFORM)                                \
  ENTRY(GL_COMPUTE_SUBROUTINE_UNIFORM)                                 \
  ENTRY(GL_TRANSFORM_FEEDBACK_VARYING)                                 \
  ENTRY(GL_ACTIVE_RESOURCES)                                           \
  ENTRY(GL_MAX_NAME_LENGTH)                                            \
  ENTRY(GL_MAX_NUM_ACTIVE_VARIABLES)                                   \
  ENTRY(GL_MAX_NUM_COMPATIBLE_SUBROUTINES)                             \
  ENTRY(GL_NAME_LENGTH)                                                \
  ENTRY(GL_TYPE)                                                       \
  ENTRY(GL_ARRAY_SIZE)                                                 \
  ENTRY(GL_OFFSET)                                                     \
  ENTRY(GL_BLOCK_INDEX)                                                \
  ENTRY(GL_ARRAY_STRIDE)                                               \
  ENTRY(GL_MATRIX_STRIDE)                                              \
  ENTRY(GL_IS_ROW_MAJOR)                                               \
  ENTRY(GL_ATOMIC_COUNTER_BUFFER_INDEX)                                \
  ENTRY(GL_BUFFER_BINDING)                                             \
  ENTRY(GL_BUFFER_DATA_SIZE)                                           \
  ENTRY(GL_NUM_ACTIVE_VARIABLES)                                       \
  ENTRY(GL_ACTIVE_VARIABLES)                                           \
  ENTRY(GL_REFERENCED_BY_VERTEX_SHADER)                                \
  ENTRY(GL_REFERENCED_BY_TESS_CONTROL_SHADER)                          \
  ENTRY(GL_REFERENCED_BY_TESS_EVALUATION_SHADER)                       \
  ENTRY(GL_REFERENCED_BY_GEOMETRY_SHADER)                              \
  ENTRY(GL_REFERENCED_BY_FRAGMENT_SHADER)                              \
  ENTRY(GL_REFERENCED_BY_COMPUTE_SHADER)                               \
  ENTRY(GL_TOP_LEVEL_ARRAY_SIZE)                                       \
  ENTRY(GL_TOP_LEVEL_ARRAY_STRIDE)                                     \
  ENTRY(GL_LOCATION)                                                   \
  ENTRY(GL_LOCATION_INDEX)                                             \
  ENTRY(GL_IS_PER_PATCH)                                               \
  ENTRY(GL_SHADER_STORAGE_BUFFER)                                      \
  ENTRY(GL_SHADER_STORAGE_BUFFER_BINDING)                              \
  ENTRY(GL_SHADER_STORAGE_BUFFER_START)                                \
  ENTRY(GL_SHADER_STORAGE_BUFFER_SIZE)                                 \
  ENTRY(GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS)                           \
  ENTRY(GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS)                         \
  ENTRY(GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS)                     \
  ENTRY(GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS)                  \
  ENTRY(GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS)                         \
  ENTRY(GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS)                          \
  ENTRY(GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS)                         \
  ENTRY(GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS)                         \
  ENTRY(GL_MAX_SHADER_STORAGE_BLOCK_SIZE)                              \
  ENTRY(GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT)                     \
  ENTRY(GL_SHADER_STORAGE_BARRIER_BIT)                                 \
  ENTRY(GL_DEPTH_STENCIL_TEXTURE_MODE)                                 \
  ENTRY(GL_TEXTURE_BUFFER_OFFSET)                                      \
  ENTRY(GL_TEXTURE_BUFFER_SIZE)                                        \
  ENTRY(GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT)                            \
  ENTRY(GL_TEXTURE_VIEW_MIN_LEVEL)                                     \
  ENTRY(GL_TEXTURE_VIEW_NUM_LEVELS)                                    \
  ENTRY(GL_TEXTURE_VIEW_MIN_LAYER)                                     \
  ENTRY(GL_TEXTURE_VIEW_NUM_LAYERS)                                    \
  ENTRY(GL_TEXTURE_IMMUTABLE_LEVELS)                                   \
  ENTRY(GL_VERTEX_ATTRIB_BINDING)                                      \
  ENTRY(GL_VERTEX_ATTRIB_RELATIVE_OFFSET)                              \
  ENTRY(GL_VERTEX_BINDING_DIVISOR)                                     \
  ENTRY(GL_VERTEX_BINDING_OFFSET)                                      \
  ENTRY(GL_VERTEX_BINDING_STRIDE)                                      \
  ENTRY(GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET)                          \
  ENTRY(GL_MAX_VERTEX_ATTRIB_BINDINGS)                                 \
  ENTRY(GL_VERTEX_BINDING_BUFFER)                                      \
  ENTRY(GL_DISPLAY_LIST)                                               \
  ENTRY(GL_STACK_UNDERFLOW)                                            \
  ENTRY(GL_STACK_OVERFLOW)                                             \
  ENTRY(GL_MAX_VERTEX_ATTRIB_STRIDE)                                   \
  ENTRY(GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED)                    \
  ENTRY(GL_BUFFER_IMMUTABLE_STORAGE)                                   \
  ENTRY(GL_BUFFER_STORAGE_FLAGS)                                       \
  ENTRY(GL_CLEAR_TEXTURE)                                              \
  ENTRY(GL_LOCATION_COMPONENT)                                         \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_INDEX)                            \
  ENTRY(GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE)                           \
  ENTRY(GL_QUERY_BUFFER)                                               \
  ENTRY(GL_QUERY_BUFFER_BARRIER_BIT)                                   \
  ENTRY(GL_QUERY_BUFFER_BINDING)                                       \
  ENTRY(GL_QUERY_RESULT_NO_WAIT)                                       \
  ENTRY(GL_MIRROR_CLAMP_TO_EDGE)                                       \
  ENTRY(GL_CONTEXT_LOST)                                               \
  ENTRY(GL_NEGATIVE_ONE_TO_ONE)                                        \
  ENTRY(GL_ZERO_TO_ONE)                                                \
  ENTRY(GL_CLIP_ORIGIN)                                                \
  ENTRY(GL_CLIP_DEPTH_MODE)                                            \
  ENTRY(GL_QUERY_WAIT_INVERTED)                                        \
  ENTRY(GL_QUERY_NO_WAIT_INVERTED)                                     \
  ENTRY(GL_QUERY_BY_REGION_WAIT_INVERTED)                              \
  ENTRY(GL_QUERY_BY_REGION_NO_WAIT_INVERTED)                           \
  ENTRY(GL_MAX_CULL_DISTANCES)                                         \
  ENTRY(GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES)                       \
  ENTRY(GL_TEXTURE_TARGET)                                             \
  ENTRY(GL_QUERY_TARGET)                                               \
  ENTRY(GL_GUILTY_CONTEXT_RESET)                                       \
  ENTRY(GL_INNOCENT_CONTEXT_RESET)                                     \
  ENTRY(GL_UNKNOWN_CONTEXT_RESET)                                      \
  ENTRY(GL_RESET_NOTIFICATION_STRATEGY)                                \
  ENTRY(GL_LOSE_CONTEXT_ON_RESET)                                      \
  ENTRY(GL_NO_RESET_NOTIFICATION)                                      \
  ENTRY(GL_COLOR_TABLE)                                                \
  ENTRY(GL_POST_CONVOLUTION_COLOR_TABLE)                               \
  ENTRY(GL_POST_COLOR_MATRIX_COLOR_TABLE)                              \
  ENTRY(GL_PROXY_COLOR_TABLE)                                          \
  ENTRY(GL_PROXY_POST_CONVOLUTION_COLOR_TABLE)                         \
  ENTRY(GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE)                        \
  ENTRY(GL_CONVOLUTION_1D)                                             \
  ENTRY(GL_CONVOLUTION_2D)                                             \
  ENTRY(GL_SEPARABLE_2D)                                               \
  ENTRY(GL_HISTOGRAM)                                                  \
  ENTRY(GL_PROXY_HISTOGRAM)                                            \
  ENTRY(GL_MINMAX)                                                     \
  ENTRY(GL_CONTEXT_RELEASE_BEHAVIOR)                                   \
  ENTRY(GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH)                             \
  ENTRY(GL_SHADER_BINARY_FORMAT_SPIR_V)                                \
  ENTRY(GL_SPIR_V_BINARY)                                              \
  ENTRY(GL_PARAMETER_BUFFER)                                           \
  ENTRY(GL_PARAMETER_BUFFER_BINDING)                                   \
  ENTRY(GL_VERTICES_SUBMITTED)                                         \
  ENTRY(GL_PRIMITIVES_SUBMITTED)                                       \
  ENTRY(GL_VERTEX_SHADER_INVOCATIONS)                                  \
  ENTRY(GL_TESS_CONTROL_SHADER_PATCHES)                                \
  ENTRY(GL_TESS_EVALUATION_SHADER_INVOCATIONS)                         \
  ENTRY(GL_GEOMETRY_SHADER_PRIMITIVES_EMITTED)                         \
  ENTRY(GL_FRAGMENT_SHADER_INVOCATIONS)                                \
  ENTRY(GL_COMPUTE_SHADER_INVOCATIONS)                                 \
  ENTRY(GL_CLIPPING_INPUT_PRIMITIVES)                                  \
  ENTRY(GL_CLIPPING_OUTPUT_PRIMITIVES)                                 \
  ENTRY(GL_POLYGON_OFFSET_CLAMP)                                       \
  ENTRY(GL_SPIR_V_EXTENSIONS)                                          \
  ENTRY(GL_NUM_SPIR_V_EXTENSIONS)                                      \
  ENTRY(GL_TEXTURE_MAX_ANISOTROPY)                                     \
  ENTRY(GL_MAX_TEXTURE_MAX_ANISOTROPY)                                 \
  ENTRY(GL_TRANSFORM_FEEDBACK_OVERFLOW)                                \
  ENTRY(GL_TRANSFORM_FEEDBACK_STREAM_OVERFLOW)

#define ENTRY(e) {e, #e},

static const std::unordered_map<GLenum, const char*> enumNames = {GL_ENUM_LIST};

namespace uinta {
const std::string getGlEnumName(const GLenum e) {
  const auto v = enumNames.find(e);
  return (v != enumNames.end()) ? v->second : "Unknown";
}
}  // namespace uinta
