# Lua and sol2 dependency for Lua scripting support
# sol2 is a modern C++ binding library for Lua
#
# IMPORTANT: sol2 v3.5.0 only supports Lua 5.1-5.4, NOT 5.5
# We use pkg-config to find system Lua 5.4 (lua54 package on Arch)

include(FetchContent)
find_package(PkgConfig REQUIRED)

# Try to find system Lua 5.4 via pkg-config
pkg_check_modules(LUA lua54)

if(LUA_FOUND)
  message(STATUS "Found system Lua 5.4: ${LUA_VERSION}")
else()
  # Fallback: fetch Lua 5.4 from source
  message(STATUS "System Lua 5.4 not found, fetching from repository...")
  FetchContent_Declare(
    lua
    GIT_REPOSITORY https://github.com/lua/lua
    GIT_TAG        v5.4.7
  )
  FetchContent_MakeAvailable(lua)

  # Build Lua as a library
  set(LUA_SOURCES
    ${lua_SOURCE_DIR}/lapi.c
    ${lua_SOURCE_DIR}/lauxlib.c
    ${lua_SOURCE_DIR}/lbaselib.c
    ${lua_SOURCE_DIR}/lcode.c
    ${lua_SOURCE_DIR}/lcorolib.c
    ${lua_SOURCE_DIR}/lctype.c
    ${lua_SOURCE_DIR}/ldblib.c
    ${lua_SOURCE_DIR}/ldebug.c
    ${lua_SOURCE_DIR}/ldo.c
    ${lua_SOURCE_DIR}/ldump.c
    ${lua_SOURCE_DIR}/lfunc.c
    ${lua_SOURCE_DIR}/lgc.c
    ${lua_SOURCE_DIR}/linit.c
    ${lua_SOURCE_DIR}/liolib.c
    ${lua_SOURCE_DIR}/llex.c
    ${lua_SOURCE_DIR}/lmathlib.c
    ${lua_SOURCE_DIR}/lmem.c
    ${lua_SOURCE_DIR}/loadlib.c
    ${lua_SOURCE_DIR}/lobject.c
    ${lua_SOURCE_DIR}/lopcodes.c
    ${lua_SOURCE_DIR}/loslib.c
    ${lua_SOURCE_DIR}/lparser.c
    ${lua_SOURCE_DIR}/lstate.c
    ${lua_SOURCE_DIR}/lstring.c
    ${lua_SOURCE_DIR}/lstrlib.c
    ${lua_SOURCE_DIR}/ltable.c
    ${lua_SOURCE_DIR}/ltablib.c
    ${lua_SOURCE_DIR}/ltm.c
    ${lua_SOURCE_DIR}/lundump.c
    ${lua_SOURCE_DIR}/lutf8lib.c
    ${lua_SOURCE_DIR}/lvm.c
    ${lua_SOURCE_DIR}/lzio.c
  )

  add_library(lua_lib STATIC ${LUA_SOURCES})
  target_include_directories(lua_lib PUBLIC ${lua_SOURCE_DIR})
  if(UNIX)
    target_compile_definitions(lua_lib PRIVATE LUA_USE_POSIX)
  endif()

  # Create lua.hpp C++ wrapper (official Lua doesn't include it)
  file(WRITE "${lua_SOURCE_DIR}/lua.hpp"
"// lua.hpp - C++ wrapper for Lua headers
// Auto-generated by cmake/lua.cmake

extern \"C\" {
#include \"lua.h\"
#include \"lualib.h\"
#include \"lauxlib.h\"
}
")

  set(LUA_LIBRARIES lua_lib)
  set(LUA_INCLUDE_DIRS ${lua_SOURCE_DIR})
endif()

# Fetch sol2 (header-only, no system package available)
# Using v3.5.0 for GCC 15 compatibility (v3.3.0 has issues with newer compilers)
message(STATUS "Fetching sol2 from repository...")
FetchContent_Declare(
  sol2
  GIT_REPOSITORY https://github.com/ThePhD/sol2
  GIT_TAG        v3.5.0
)
FetchContent_MakeAvailable(sol2)

# Create an interface library for easy linking
# Use BEFORE to ensure Lua 5.4 headers take precedence over any system Lua 5.5
add_library(uinta_lua INTERFACE)
target_link_libraries(uinta_lua INTERFACE ${LUA_LIBRARIES} sol2)
target_include_directories(uinta_lua BEFORE INTERFACE ${LUA_INCLUDE_DIRS})

list(APPEND UINTA_LIBS uinta_lua)
